version: '3'
services:  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:      